#!/usr/bin/env python

import sys

PYTHONDIR='/usr/lib/python2.7/site-packages'
sys.path.append(PYTHONDIR)

from srt2R.main import Srt2RApplication
from PyQt4 import QtGui, QtCore

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    myapp = Srt2RApplication()
    myapp.show()
    sys.exit(app.exec_())
